title: Nicolas Gendron-Carrier
author: Nicolas Gendron-Carrier

url: "http://nigeca.github.io"
baseurl: "/ngc_carnival"

description: "Nicolas Gendron-Carrier is a PhD candidate in Economics at the University of Toronto. His research interests are in labour economics and urban economics."

tracking_id: UA-69692111-2

sass:
    style: compressed
    sass_dir: _sass

include: ['_pages']

kramdown:
    input: GFM